{{- if .Values.rca.anteater.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gala-anteater-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: anteater-{{ .Release.Name }}
  ports:
    - port: 5210
      targetPort: 5210
{{- end }}